name: Merge TXT Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 1,10,17 * * *'   # 每天在 UTC 时间 1:15、10:15 和 17:15 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  merge_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Remove old merged file
        run: rm -f dszb.txt  # 

      - name: Run merge script
        run: python zb.py  # 

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dszb.txt
          git commit -m '自动合并 TXT 文件' || echo "No changes to commit"
          git push
