name: zubo

on:
#  schedule:
- cron: '0 7,15,23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: 获取组播地址
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x speed.sh
        bash ./zubo.sh

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x

    - name: Install dependencies
      run: |
          pip install selenium requests futures eventlet
#         pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1

    - name: run 去重py
      run: python ${{ github.workspace }}/去重.py
      
    - name: 更新组播源
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新组播源"
        git push
